# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application (PMML, Nightly Build)

on:
  schedule:
#    - cron: 00 03 * * *
    - cron: 00 * * * *

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    defaults:
      run:
          working-directory: pmml
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run All Steps (1-3)
      run: |
        python run_all_steps.py
    - name: Git Commit
      run: |
        git add step1_prepare/*
        git add step2_train/*
        git add step3_predict/*
        git commit -m 'chore(ml): nightly build'
    - name: Git Push
      run: |
        git push
